# Generated by Django 5.2 on 2025-04-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_cip_document_customuser_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
