# Generated by Django 5.2 on 2025-04-21 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_rejected_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Le nom d'utilisateur ne peut contenir que des lettres, chiffres, espaces, et @/./+/-/_", regex='^[\\w\\s.@+-]+$')]),
        ),
    ]
