# Generated by Django 5.2 on 2025-04-16 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plastique', 'Plastique'), ('papier', 'Papier'), ('organique', 'Organique'), ('electronique', 'Électronique'), ('autre', 'Autre')], max_length=20)),
                ('weight', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='waste_photos/')),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(default='en attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
