# Generated by Django 5.2 on 2025-04-21 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedeclaration',
            name='collector',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'collecteur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_declarations', to=settings.AUTH_USER_MODEL),
        ),
    ]
