# Generated by Django 5.2 on 2025-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0002_wastedeclaration_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedeclaration',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastedeclaration',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastedeclaration',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastedeclaration',
            name='collection_date',
            field=models.DateField(blank=True, help_text='Date prévue pour la collecte', null=True),
        ),
        migrations.AlterField(
            model_name='wastedeclaration',
            name='status',
            field=models.CharField(choices=[('en attente', 'En attente'), ('attribué', 'Attribué'), ('accepté', 'Accepté'), ('refusé', 'Refusé'), ('collecté', 'Collecté')], default='en attente', max_length=20),
        ),
    ]
